# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Forge < Formula
  desc "Unified software modeling DSL — architecture diagrams, docs, and lint from code"
  homepage "https://github.com/grahambrooks/forge"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.10.1/forge-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "41f70c4cac3cc4160012ffa0a94f99bccac6199edd9cbfaff981a59a1ba09d01"
    end
    on_intel do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.10.1/forge-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "0e3426b53bf5842ae225ce57f3448cb10c3908cebac2ac5b001b7fd02a007853"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.10.1/forge-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f06500f12e644d90e22a6543d43c6a4e75d01e1c5f3667a7c5d651c45c5f0f60"
    end
    on_intel do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.10.1/forge-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "780e9b67ae5c4437b8c7fdbbdd5b4b43273d24f5a17d1473344225b6f4c06ded"
    end
  end

  def install
    bin.install "forge"
  end

  test do
    assert_path_exists bin/"forge"
  end
end
