# Generated by scripts/release.py (release-kit) from the v2026.9.8 release — do not edit.
class Forge < Formula
  desc "Unified software modeling DSL — architecture diagrams, docs, and lint from code"
  homepage "https://github.com/grahambrooks/forge"
  version "2026.9.8"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.9.8/forge-v2026.9.8-aarch64-apple-darwin.tar.gz"
      sha256 "1b73b5e5e9ca556780590cb25847cd81328fede4e089b4a5ba1113c7b9365c4c"
    end
    on_intel do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.9.8/forge-v2026.9.8-x86_64-apple-darwin.tar.gz"
      sha256 "3700ea405f1ebeb58bf41f59646bf7ff2887111d14dbb8d52d301bb1ac054669"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.9.8/forge-v2026.9.8-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6fedd56884e50b38197f691904ec7b6313f0c2cf58cd5e1ef75edaae068cad25"
    end
    on_intel do
      url "https://github.com/grahambrooks/forge/releases/download/v2026.9.8/forge-v2026.9.8-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d9e31d9450f84d0a2e423022cdaf17ff3f815aaf8962f1f67494b4691426869f"
    end
  end

  def install
    bin.install "forge"
  end

  test do
    assert_path_exists bin/"forge"
  end
end
